import 'package:freezed_annotation/freezed_annotation.dart';

part 'product.freezed.dart';


// Product Class Generated by freeze, abstratcs away [copyWith, ==, hascode methods]

@freezed
class Product with _$Product {
  @override
  final String title;
  @override
  final double price;
  @override
  final String description;
  @override
  final List<String> productTags;

  Product({
    required this.title,
    required this.price,
    required this.description,
    required this.productTags,
  });
}
